language: cpp

sudo: false

dist: focal

branches:
  only:
    - master

compiler:
  - clang
  - gcc

before_script:
  - ci/travis-install-eigen3.sh
  - mkdir build
  - cd build
  - cmake .. -DTESTS=ON -DCMAKE_BUILD_TYPE=Release -DEigen3_DIR=$HOME/local/share/eigen3/cmake

cache:
  directories:
    - $HOME/local

script:
  - make
  - ./controltests
  - cd ../
  - ci/travis-install-doxygen.sh
  - $HOME/local/doxygen Doxyfile

deploy:
  edge:
    branch: v1.8.47
  provider: pages
  skip_cleanup: true
  local_dir: docs/html
  keep-history: true
  github_token: $GH_REPO_TOKEN
  on:
    branch: master
    condition: $CC = gcc
